/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DocumentProvider } from "./lib/document/provider";
import { InteractionMode } from "./components/document-viewer/document-viewer";
import { DocumentApiState } from "./lib/document/api";
import { Point } from "@vertexvis/geometry";
export { DocumentProvider } from "./lib/document/provider";
export { InteractionMode } from "./components/document-viewer/document-viewer";
export { DocumentApiState } from "./lib/document/api";
export { Point } from "@vertexvis/geometry";
export namespace Components {
    interface VertexDocumentViewer {
        /**
          * Common state of the current document. This value includes information common to all types of documents, including state like zoom percentage, viewport definition, and offsets.
         */
        "documentState"?: DocumentApiState;
        /**
          * The interaction mode for the viewer. When set to `'pan'`, click and drag will pan the document. When set to `'none'`, no pointer interactions are registered.
          * @default 'pan'
         */
        "interactionMode": InteractionMode;
        /**
          * Pans the currently loaded document by the specified delta.  This method will be bounded to the visible portion of the document to ensure at least a portion of the document is always visible, and the `canvas` does not appear blank.
          * @param delta The delta to pan the document by.
         */
        "panByDelta": (delta: Point.Point) => Promise<void>;
        /**
          * The provider used to create the document API and renderer.
          * @default new PdfJsProvider()
         */
        "provider": DocumentProvider;
        /**
          * An optional value that will debounce image updates when resizing this viewer element.
          * @default 100
         */
        "resizeDebounce": number;
        /**
          * A URI of the document to load when the component is mounted in the DOM tree. Currently only supports URLs for client-side rendering.
         */
        "src"?: string;
        /**
          * Zooms the currently loaded document to the specified zoom percentage.  This method will automatically adjust existing offsets to maintain the same center point of the document where possible.
          * @param percentage The zoom percentage to set.
         */
        "zoomTo": (percentage: number) => Promise<void>;
    }
}
declare global {
    interface HTMLVertexDocumentViewerElement extends Components.VertexDocumentViewer, HTMLStencilElement {
    }
    var HTMLVertexDocumentViewerElement: {
        prototype: HTMLVertexDocumentViewerElement;
        new (): HTMLVertexDocumentViewerElement;
    };
    interface HTMLElementTagNameMap {
        "vertex-document-viewer": HTMLVertexDocumentViewerElement;
    }
}
declare namespace LocalJSX {
    interface VertexDocumentViewer {
        /**
          * Common state of the current document. This value includes information common to all types of documents, including state like zoom percentage, viewport definition, and offsets.
         */
        "documentState"?: DocumentApiState;
        /**
          * The interaction mode for the viewer. When set to `'pan'`, click and drag will pan the document. When set to `'none'`, no pointer interactions are registered.
          * @default 'pan'
         */
        "interactionMode"?: InteractionMode;
        /**
          * The provider used to create the document API and renderer.
          * @default new PdfJsProvider()
         */
        "provider"?: DocumentProvider;
        /**
          * An optional value that will debounce image updates when resizing this viewer element.
          * @default 100
         */
        "resizeDebounce"?: number;
        /**
          * A URI of the document to load when the component is mounted in the DOM tree. Currently only supports URLs for client-side rendering.
         */
        "src"?: string;
    }

    interface VertexDocumentViewerAttributes {
        "src": string;
        "interactionMode": InteractionMode;
        "resizeDebounce": number;
    }

    interface IntrinsicElements {
        "vertex-document-viewer": Omit<VertexDocumentViewer, keyof VertexDocumentViewerAttributes> & { [K in keyof VertexDocumentViewer & keyof VertexDocumentViewerAttributes]?: VertexDocumentViewer[K] } & { [K in keyof VertexDocumentViewer & keyof VertexDocumentViewerAttributes as `attr:${K}`]?: VertexDocumentViewerAttributes[K] } & { [K in keyof VertexDocumentViewer & keyof VertexDocumentViewerAttributes as `prop:${K}`]?: VertexDocumentViewer[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vertex-document-viewer": LocalJSX.IntrinsicElements["vertex-document-viewer"] & JSXBase.HTMLAttributes<HTMLVertexDocumentViewerElement>;
        }
    }
}
