/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VertexDocumentViewer {
        /**
          * An optional value that will debounce image updates when resizing this viewer element.
          * @default 100
         */
        "resizeDebounce": number;
        /**
          * A URI of the document to load when the component is mounted in the DOM tree. Currently only URLs are supported.
         */
        "src"?: string;
    }
}
declare global {
    interface HTMLVertexDocumentViewerElement extends Components.VertexDocumentViewer, HTMLStencilElement {
    }
    var HTMLVertexDocumentViewerElement: {
        prototype: HTMLVertexDocumentViewerElement;
        new (): HTMLVertexDocumentViewerElement;
    };
    interface HTMLElementTagNameMap {
        "vertex-document-viewer": HTMLVertexDocumentViewerElement;
    }
}
declare namespace LocalJSX {
    interface VertexDocumentViewer {
        /**
          * An optional value that will debounce image updates when resizing this viewer element.
          * @default 100
         */
        "resizeDebounce"?: number;
        /**
          * A URI of the document to load when the component is mounted in the DOM tree. Currently only URLs are supported.
         */
        "src"?: string;
    }

    interface VertexDocumentViewerAttributes {
        "src": string;
        "resizeDebounce": number;
    }

    interface IntrinsicElements {
        "vertex-document-viewer": Omit<VertexDocumentViewer, keyof VertexDocumentViewerAttributes> & { [K in keyof VertexDocumentViewer & keyof VertexDocumentViewerAttributes]?: VertexDocumentViewer[K] } & { [K in keyof VertexDocumentViewer & keyof VertexDocumentViewerAttributes as `attr:${K}`]?: VertexDocumentViewerAttributes[K] } & { [K in keyof VertexDocumentViewer & keyof VertexDocumentViewerAttributes as `prop:${K}`]?: VertexDocumentViewer[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vertex-document-viewer": LocalJSX.IntrinsicElements["vertex-document-viewer"] & JSXBase.HTMLAttributes<HTMLVertexDocumentViewerElement>;
        }
    }
}
