name: Publish Testing

on:
  push:
    branches:
      - publish-testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout changes"
        uses: actions/checkout@v2
      - name: Set Node Version
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: "Install"
        run: "yarn install --frozen-lockfile"
      - name: "Build"
        run: "yarn build"
      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: |
            packages/*/dist
            packages/viewer/loader
  publish-testing:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: "Checkout changes"
        uses: actions/checkout@v2
      - name: "Download build artifacts"
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: packages
      - name: Set Node Version
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          registry-url: https://registry.npmjs.org
          scope: "@vertexvis"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: "Install"
        run: "yarn install"
      - name: "Publish Testing build to NPM"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPMJS_ACCESS_TOKEN }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./scripts/publish_testing.sh